export type CompressionFormat = "jpg" | "webp" | "png";
export type CompressionPreset = "high-quality" | "balanced" | "small-size" | "custom";
export type CompressionOutputLocation = "source" | "subfolder" | "directory";
export type MetadataPolicy = "preserve" | "strip" | "stripAll" | "stripSafe";
export interface CompressionItem { id: string; file: File; sourcePath?: string; size: number; dimensions?: { width: number; height: number }; }
export type CompressionItemResultStatus = "completed" | "skipped" | "failed";
export interface CompressionQualityMetrics { rgbMae: number; psnrDb: number | null; alphaMismatchPixels: number; }
export interface CompressionItemResult { itemId?: string; fileName: string; status: CompressionItemResultStatus; outputPath?: string; reason?: string; nativeReason?: string; sourceDeleted?: boolean; inputBytes?: number; outputBytes?: number; savedBytes?: number; savingsPercent?: number; width?: number; height?: number; selectedResizePercent?: number; autoResizeToTarget?: boolean; candidateSearchMs?: number; candidateCount?: number; qualityMetrics?: CompressionQualityMetrics; }
export interface CompressionOptions { format: CompressionFormat; quality: number; webpMethod?: number; webpAlphaQuality?: number; webpPass?: number; webpNearLossless?: number | null; webpLosslessMethod?: number | null; pngOptimizeAlpha?: boolean; jpegBackground?: string; jpegProgressive?: boolean; jpegOptimizeHuffman?: boolean; lossless: boolean; pngOptimizationLevel: number; metadataPolicy: MetadataPolicy; outputLocation: CompressionOutputLocation; outputFileName?: string; outputSubdirectory?: string; outputDirectory?: string; overwrite: boolean; autoNumbering?: boolean; replaceOriginal?: boolean; deleteSource?: boolean; skipIfLarger?: boolean; maxOutputBytes?: number; maxCandidates?: number; maxRgbMae?: number | null; targetResizePercent?: number | null; autoResizeToTarget?: boolean; maxInputBytes?: number; }
export interface CompressionEstimate { inputBytes: number; originalInputBytes?: number; preparedInputBytes?: number; estimatedBytes: number; savingsPercent: number; width?: number; height?: number; selectedResizePercent?: number; autoResizeToTarget?: boolean; metadataPolicy?: MetadataPolicy; compressionMode?: "lossless" | "lossy"; compressionEngine?: "oxipng" | "image-jpeg" | "jpeg-encoder" | "libwebp"; maxRgbMae?: number | null; qualityMetrics?: CompressionQualityMetrics; candidateSearchMs?: number; candidateCount?: number; targetBytes?: number | null; targetMet?: boolean; selectedQuality?: number | null; status?: "completed" | "skipped"; skippedReason?: string | null; }
